<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
   <div class="product-filters">
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        
       
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                       <div class="filter-col brand-filter">
                       
                    <?php  $wrapOptions = true; endif; ?>
                         <ul class="filter-dropdown">
                        <a href="javascript:void(0);" class="filter-link"><?php /* @escapeNotVerified */ echo __('Filter by '.$filter->getName()) ?></a>
                        <?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>
                        </ul>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
            
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
       
    </div>
<?php endif; ?>



