<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>

<div class="product_inner_section">	
	
	<?php if($_product['show_subscribe']=='1'){?>
	<div class="subscribe">
	<div class="sub_text">Subscribe + Save 10% </div>
	<div class="onoffswitch-sub">
     <input type='checkbox' name='opt2' id='opt2' value='1' class='toggleswitch' />
	</div>
	</div>
	<div class="subscribe_learn"><a href="<?php echo $this->getUrl('subscribe-learn-more') ?>">Learn More</a></div>
	<?php }?>							
								
								
								
								
<div class="qty_section">
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty qty-col">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="qty-container">
              <div class="qty-input">
			  <button type="button" class="btnMin">-</button>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
				<button type="button" class="btnAdd">+</button>
            </div>
			 </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
</div>
<?php endif; ?>


<div class="demand_section">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('stock-massage')->toHtml(); ?>	
</div>
</div>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>


<script type="text/javascript"> 
require(["jquery"], function(jQuery){
  jQuery(document).ready(function(){
    jQuery('.btnAdd').click(function() {
		//alert('+++')
      var oldVal = jQuery(this).parent().find("input").val();
      if ( parseFloat(oldVal) >= 1 ) {
        var newVal = parseFloat(oldVal) + 1;
        jQuery(this).parent().find("input").val(newVal);
      }
    });

    jQuery('.btnMin').click(function() {
      var oldVal = jQuery(this).parent().find("input").val();
      if ( parseFloat(oldVal) >= 2 ) {
        var newVal = parseFloat(oldVal) - 1;
        jQuery(this).parent().find("input").val(newVal);
      }
    });
  });
  });
</script>


<script type ="text/javascript">
require(["jquery"], function($){
(function ($) {
    'use strict';
    $.fn.toggleSwitch = function (options) {
        var settings = $.extend({
            onClick: function () { return true; },
            onChangeOn: function () { return true; },
            onChangeOff: function () { return true; }
        }, options);
        $(this).each(function () {
            var obj = $(this), status = obj.is(':checked') ? '' : ' off';
            if (!obj.parent('div.switch').length) {
                obj.wrap('<div class="switch"></div>');
                obj.parent('div.switch').prepend('<span class="switched' + status + '" />').prepend('<div class="overlay" />');
            }
            obj.parent('div.switch').add($('label[for=' + obj.prop('id') + ']')).click(function (e) {
                e.preventDefault();
                if (!obj.prop('disabled')) {
                    var value, check;
                    settings.onClick.call(obj);
                    if ($(this).is('label')) {
                        value = $('#' + $(this).prop('for')).prev('span.switched');
                        check = $('#' + $(this).prop('for'));
                    } else {
                        value = $(this).children('span.switched');
                        check = $(this).children('input[type=checkbox]');
                    }
                    if (value.is('.off')) {
                        value.stop().animate({left: 0}, 150, 'linear').removeClass('off');
                        check.prop('checked', 'checked');
                        settings.onChangeOn.call(obj);
                    } else {
                        value.stop().animate({left: -21}, 150, 'linear').addClass('off');
                        check.prop('checked', '');
                        settings.onChangeOff.call(obj);
                    }
                }
            });
        });
    };
}(jQuery)); 
	 
 $(document).ready(function($) {
	  $('.toggleswitch').toggleSwitch();
	  $("#opt2").trigger("click"); // turn it on
	});
 });	 
</script>