<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <!--<div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>-->
                <!--<div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                
                </div>-->
                   
                <?php if($alias != 'additional') {?>				   
				
 				<?php if($alias != 'reviews') {?>	
				<div class="review_section">
				<div class="label-reviews-title"> Reviews </div>
				<button type="submit" title="write a review" class="action primary write-a-review" ><span>write a review</span></button>
				<div  class ="all-product-<?= /* @escapeNotVerified */ $alias ?>"> <?= /* @escapeNotVerified */ $html ?> 
				   
				<span id="<?= /* @escapeNotVerified */ $alias ?>"></span>
				</div>
				
				</div>
				<?php } else { ?>
				<div  class ="all-product-<?= /* @escapeNotVerified */ $alias ?>"> <?= /* @escapeNotVerified */ $html ?> </div>
				<?php }?>
				
				
				   
				 <?php } ?>  
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>


<?php //echo $this->getUrl('review/product/listAjax/id/1/')?>
<script type="text/javascript">
require([ 'jquery'], function($){
jQuery(document).ready(function($){
   $.ajax({
        url: "<?php echo $this->getUrl('review/product/listAjax/id/1/')?>",
        type: "GET",
        //data:  {"id":obj,"vediourl":vediourl},
        success: function(response){
			//alert(response);
		$('#reviews').html(response);	
		
        }
	  });
 
});
});
</script>