<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog sidebar categories template
 *
 * @var $block \Saffron\Blog\Block\Sidebar\Categories
 */
?>

<?php $items = $this->getGroupedChilds(); ?>

<?php if (count($items)) { ?>

<div class="widget block block-categories" data-bind="scope: 'categories'">
    <div class="block-title">
        <strong><?php echo __('Categories') ?></strong>
    </div>

	<ul class="accordion"  id="accordion-2">
	<?php
		$level = 0;
		$first = true;
		foreach($items as $item) {
			$newLevel = $item->getLevel();

			if ($level == $newLevel && !$first) {
				echo '</li>';
			}

			if ($level < $newLevel) {
				echo '<ul>';
			}

			if ($level > $newLevel) {
				for ($i = $level; $i > $newLevel; $i--){
					echo '</ul></li>';
				}
			}

			
		  $categoriesdata = $item->getData();
			
			?>
			
			
				<li>
					<a href="javascript:void(0);<?php //echo $item->getCategoryUrl() ?>"  onclick="getCategoryid(<?php echo $categoriesdata['category_id']?>)" >
						<?php echo $block->escapeHtml($item->getTitle()) ?>
					</a>
			<?php
			$level = $newLevel;
			$first = false;
		}
	?>
	</ul>
</div> 
<?php } ?>

<span id="recent-blog"></span>


<script>
function getCategoryid(obj){
	
jQuery(document).ready(function($){
  $("#loderpop").addClass("showpopup");
  
  $.ajax({
        url: "<?php echo $this->getBaseUrl()?>/blog/category/view/",
        type: "GET",
        data:  {"id":obj},
        success: function(response){
		$('#recent-blog').html(response);	
		$("#loderpop").removeClass("showpopup");
        }
	  });
 
});
	
}
</script>