<?php
	$isLoggedIn = $block->isLoggedIn();
?>
<div class="user-dropdown">
	<div class="sign-col">
		<a href="javascript:void(0);" class="singin-link">
			<i class="fa fa-user-o" aria-hidden="true"></i>
		</a>
		<div class="singin-dropdown">
		<ul>
		<?php if($isLoggedIn): ?>
		<li><a href="<?php echo $this->getUrl('customer/account/'); ?>">Account</a></li>
		<li><a href="<?php echo $this->getUrl('find-a-store/'); ?>">Find a Store </a></li>
		<li><a href="<?php echo $this->getUrl('customer/account/logout/'); ?>">Log Out</a></li>
		<?php else :?>
		 <li><a href="<?php echo $this->getUrl('customer/account/login/'); ?>">Sign In</a></li>
		 <li><a href="<?php echo $this->getUrl('customer/account/create/'); ?>">Create Account</a></li>
		 <li><a href="<?php echo $this->getUrl('find-a-store/'); ?>">Find a Store </a></li>
		<?php endif; ?>	  
		</ul>
	</div>
	</div>

</div>

<div class="navbar-col">
	<button class="menuBtn bar-button">
		<span class="menubar menubar1"></span>
		<span class="menubar menubar2"></span>
		<span class="menubar menubar3"></span>
	</button>
</div>
	
	

   
<script type="text/javascript">
	require([ 'jquery'], function($){

$(document).ready(function(){	

 //menu 
   $(".navbar-col .bar-button").on("click", function(){
        $(".nav-sections").addClass('open');
    })
    $(".nav-sections-items .bar-button").on("click", function(){
        $(".nav-sections").removeClass('open');
		 
    })
    $(".navbar-col .menuBtn").on("click", function(){
        $("body").addClass('menu-open');
    })
    $(".nav-sections-items .menuBtn").on("click", function(){
        $("body").removeClass('menu-open');
    })

    //new-menu-js
    $(".menu-parent li.menu-item  .fa").on("click", function(){
        $(".navbar-body").removeClass('active');
    })
    $(".home-level a").on("click", function(){
        $(".navbar-body").removeClass('active');
        $(".menu-item-front").addClass("active");
    });
    $(".menu-parent li.labs-menu .fa").on("click", function(){
        $(".menu-item-labs").addClass('active');
    })
    $(".menu-parent li.worx-menu .fa").on("click", function(){
        $(".menu-item-worx").addClass('active');
    })
    $(".menu-parent li.cbdx-menu .fa").on("click", function(){
        $(".menu-item-cbdx").addClass('active');
    })
    $(".menu-parent li").on("click", function(){
        $(this).addClass("active");
        $(this).siblings().removeClass("active");
    })
	
	//mousehover menu script for >= 1025
	if ($(window).width() >= 1025) {
		$(".nav-sections-items .menuBtn").on('click', function(){
			$(".navbar-body").siblings().removeClass("hover-active");
		})
		$(".menu-parent li .fa").on("click", function(){
			$(".navbar-body").siblings().removeClass("hover-active");
		})
		$(".menu-parent li.menu-item.labs-menu").on('mouseenter', function(e){
			$(".navbar-body").siblings().removeClass("hover-active");
			$(".navbar-body.menu-item-labs").addClass("hover-active");
			
		})
		$(".menu-parent li.menu-item.worx-menu").on('mouseenter', function(){
			$(".navbar-body").siblings().removeClass("hover-active");
			$(".navbar-body.menu-item-worx").addClass("hover-active");
		})
		$(".menu-parent li.menu-item.cbdx-menu").on('mouseenter', function(){
			$(".navbar-body").siblings().removeClass("hover-active");
			$(".navbar-body.menu-item-cbdx").addClass("hover-active");
		})
	}
    
    //end-menu 
    
 var $item = $('.front-banner .item'); 
    var $wHeight = $(window).height();
    $item.eq(0).addClass('active');
    $item.height($wHeight); 
    
    $(window).on('resize', function (){
      $wHeight = $(window).height();
      $item.height($wHeight);
    });
    // End- LV8-Labs-Worx-Cbdx home page banner script


    //cbdx product tab title script
   

    //cbdx product filter script
    $(".filter-col .filter-link").on("click", function(e){
		e.stopPropagation();
		$(this).toggleClass('active');
        $(this).next('ul').slideToggle();
       // $(this).parent().siblings().children().next().slideUp();
    });
    $(".filter-dropdown li a").on("click", function(){
        $(".filter-dropdown li a").removeClass("active");
        $(this).addClass("active");
    });
	$(document).click( function(){
		$(".filter-col .filter-link").removeClass('active');
		$(".filter-dropdown").slideUp();
	});
    
    //banefit page circle js
	if( $(window).width() <= 1024 ){
		$(".point .point-circle").on("click", function(){
			$(this).addClass("active");
			$(this).parent().siblings().children().removeClass("active");
			$(this).next().slideToggle();
			$(this).parent().siblings().children().next().slideUp();
		})
	}
	$(window).resize(function(){
		if( $(window).width() <= 1024 ){
		$(".point .point-circle").on("click", function(){
			$(this).addClass("active");
			$(this).parent().siblings().children().removeClass("active");
			$(this).next().slideToggle();
			$(this).parent().siblings().children().next().slideUp();
		})
	}
	});
	$(".point-body .closeBtn").on("click", function(){
		$(this).parent().fadeOut();	
		$(this).parent().siblings("span").removeClass('active');
	});
	
    
    
    // scroll menu click respectively #div 
    $(".scrollMenu a, .cbdx-brands-col .brand-link").on("click", function(){
        //event.preventDefault();
        $(".nav-sections").removeClass('open');
        $("body").removeClass('menu-open');
       $("html, body").animate( { scrollTop: $($(this).attr("href") ).offset().top-40 }, 1000 );
      
    })
 
	
	//header user dropdown js
	$(document).click( function(){
		$(".singin-dropdown").slideUp();
	})
	$(".sign-col .singin-link").on("click", function(e){
		e.stopPropagation();
		$(".header .block-search .block-content").hide();	
		$(this).toggleClass('active');
		$(".singin-dropdown").slideToggle();
	})
 
   $(".mobile-arrow .scroll-down").on("click", function(){
		$('html, body').animate({
			scrollTop: $(window).height()
		}, 700);
	});
   
   $(".information-mobile span").on("click", function(){
		$(this).parent().toggleClass('open');
		$(this).parent().next(".info-title-list").slideToggle();	
	})
	
	$(".menu-item-worx .adrs-col li a, .menu-item-labs .adrs-col li a").on("click", function(){
		$(".nav-sections").removeClass('open');
		$("body").removeClass('menu-open');
		
	})
	
	
	//header search script
	$(".block.block-search .block.block-title strong").on("click", function(e){
		e.stopPropagation(); 
		$(".header .block-search .block-content").show();
		$(".singin-dropdown").slideUp();
	});

	$(".header .block.block-search").on("click", function(e){
		e.stopPropagation(); 
	});	
	$(document).on("click", function(){
		$(".header .block-search .block-content").hide();	
	});
	
	$(".minicart-wrapper .action.showcart").on("click", function(){
		$(".header .block-search .block-content").hide();
		$(".sign-col .singin-dropdown").slideUp();
	});

	
	

 
  /*  require([ "jquery","aos/js"], function($,aos){ 
     AOS.init();	
	 $(window).on('load', function() {
		AOS.refresh();
     });
	
    });
	
	
require([ "jquery","bootstrap"], function(jquery,bootstrap){ 
     jquery(document).ready(function() {
   jquery('#exampleModal').modal('show');
     });
	
    });*/
	
	
	//header scroll		 
	jQuery(window).scroll(function(){
		if(jQuery(window).scrollTop()> 120 ){
			jQuery('.page-layout-1column .page-header').addClass('header-sticky');
		}
		else {
			jQuery('.page-layout-1column .page-header').removeClass('header-sticky');
		}
	  }) ;
	  
	  
jQuery(".review-container button.write-a-review").on('click', function(){
    jQuery(".review-add").slideToggle();
});
	
});	


//internshil collapse jquery
jQuery(".faq-row.active .answer").show();
jQuery(".faq-row h4").on("click", function(){
	jQuery(this).parent().toggleClass('active');
    jQuery(this).next().slideToggle();
	jQuery(this).parent().siblings().removeClass('active').children('.answer').slideUp();
});

//cbdx menu brands logo scroll js 
jQuery(".cbdx-brands-col .brand-link").on("click", function(){
	alert();
	jQuery("html, body").animate( { scrollTop: jQuery(jQuery(this).attr("href") ).offset().top-200 }, 1000 
 );
  
})


//category page on scroll category fix javascript
	var $banner = jQuery(".catalog-category-view .banner-breadcrumbs").height();
	var $category = jQuery(".catalog-category-view .product-tab-title");
	jQuery(window).scroll(function() { 
		var $scroll = jQuery(window).scrollTop();    
		if (  $scroll > $banner ) {
			$category.addClass('category-sticky');
		}
		else{
			$category.removeClass('category-sticky');
		}
	}); 
	//end




	});
</script>
<script type="text/javascript">
	
	require([
	  "jquery",
	  "owlcarousel/minjs"
	 ], function($,owlCarousel){
		$(document).ready(function(){
		$('.theBrands-carousel .owl-carousel').owlCarousel({
    loop:true,
    items:1,
    margin:0,
    nav:true,
    dots:false,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    smartSpeed: 500,
   
}) ;
$('.stories-carousel .owl-carousel').owlCarousel({
    loop:true,
    items:1,
    margin:0,
    nav:true,
    dots:false,
    smartSpeed:500,
  
});
	
$('.promoting-carousel .owl-carousel').owlCarousel({
    loop:true,
    margin:40,
    nav:true,
    dots:false,
    smartSpeed: 500,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
});    

//customer-say carousel
$('.customer-carousel .owl-carousel').owlCarousel({
    loop:true,
    items:1,
    margin:0,
    nav:true,
    dots:false,
    smartSpeed: 500,
  
});

	
	
	});
});
</script>
<script type="text/javascript">
    require(['aos'], function (AOS) {
		AOS.init({
                  duration: 500,
         });	
		
	
	 });
	 


	

</script>	

