<div class="navbar-col">
                    <button class="menuBtn bar-button">
                        <span class="menubar menubar1"></span>
                        <span class="menubar menubar2"></span>
                        <span class="menubar menubar3"></span>
                    </button>
  </div>
	
	
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Subscribe our Newsletter</h4>
            </div>
            <div class="modal-body">
				<p>Subscribe to our mailing list to get the latest updates straight in your inbox.</p>
                <form>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email Address">
                    </div>
                    <button type="submit" class="btn btn-primary">Subscribe</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
 /*requirejs(['jquery', 'jquery.bootstrap'], function (jQuery, jQueryBootstrap) {
  jQuery(document).ready(function(){
        jQuery("#myModal").modal('show');
    });
    });*/
</script>
   
<script type="text/javascript">
	require([ 'jquery'], function($){

$(document).ready(function(){	

 $(".navbar-col .bar-button").on("click", function(){
        $(".custom-menu").toggleClass('open');
    })
    $(".menubar-close").on("click", function(){
        $(".custom-menu").removeClass('open');
    })
    

 
  /*  require([ "jquery","aos/js"], function($,aos){ 
     AOS.init();	
	 $(window).on('load', function() {
		AOS.refresh();
     });
	
    });
	
	
require([ "jquery","bootstrap"], function(jquery,bootstrap){ 
     jquery(document).ready(function() {
   jquery('#exampleModal').modal('show');
     });
	
    });*/
	
});	


	});
</script>

	
<style>
.header.content {
    display: none;
}

</style>