<div class="menu-button-content">
	<div class="menu-button in-menu">
		<div></div>
		<div></div>
		<div></div>
	</div>
</div>

<?php /* <a href="#" class="shop-button"><?php echo __('Shop') ?></a> */ ?>

<div class="left-menu">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('explore_menu')->toHtml();?>
</div>

<script type="text/javascript">
	require([ 'jquery'], function($){

	   
	
		$(document).ready(function(){	


			var lastScrollTop = 80;
			$(window).scroll(function(event){
			   var st = $(this).scrollTop();
			   if (st > lastScrollTop){
			       
			    	$('.page-header').addClass('header-scroll'); 	
			       
			   } else {
			    	$('.page-header').removeClass('header-scroll');
			      
			   }
			   lastScrollTop = st;
			});
			
			//new custom scroll add class for mobile
			if( $(window).width() <=767 ){
				$(window).scroll(function(event){
					if($(window).scrollTop()> 80 ){
						$('header').addClass('header-scroll2');
					}
					else {
						$('header').removeClass('header-scroll2');
					}
				});	
			}
			
			
		
			
			

			$('.in-menu').click(function(evt){
                evt.stopPropagation();
				$('.left-menu').addClass('open');
				$(this).hide();
				$('.button-content-cms').show(); 
			});
			$('body').click(function(){
				$('.left-menu').removeClass('open');
				$('.in-menu').show();
				$('.button-content-cms').hide();
			});
            $('.in-cms').click(function(){
                $('.left-menu').removeClass('open');
                $('.in-menu').show();
                $('.button-content-cms').hide();
            });
            $('.left-menu').click(function(evt) { evt.stopPropagation(); });
            
			
			
					
			//explore menu script
			// $('.explore_menu .heading-medium').click(function(){
				// $('.explore_menu .sub_menu').slideUp();
				// $(this).next('.explore_menu .sub_menu').slideToggle();
				// $('.explore_menu .heading-medium').parent('li').removeClass('active');
				// $(this).parent('li').addClass('active');
			// })
			
			$('.explore_menu .heading-medium').on('click', function() {
			  $('.explore_menu .heading-medium').removeClass('active');
			  $(this).addClass('active');
			  var $box = $(this).closest('.explore_menu');
			  $box.siblings().find('.sub_menu').stop().slideUp();
			  $box.find('.sub_menu').stop().slideToggle();
			 })
			 
	//header scroll		 
	jQuery(window).scroll(function(){
		if(jQuery(window).scrollTop()> 120 ){
			jQuery('.page-layout-1column .page-header').addClass('header-sticky');
		}
		else {
			jQuery('.page-layout-1column .page-header').removeClass('header-sticky');
		}
	  }) ;

		});	


	});
</script>

