<?php
/**
 * Copyright © 2015 Saffron.com. All rights reserved.

 * @author Saffron Team <contact@Saffron.com>
 */
 
if($this->getEnable()):
$banners = $block->getBannerSlider();
?>
<!--<div class="front-banner" >
        <div class="owl-carousel owl-theme">
		<?php $i = 1; ?>
    <?php foreach ($banners as $banner): ?>
	
	    
	
	<?php $url_image = $this->getMediaFolder().$banner['image']; ?>
	
	<?php if(!empty($banner['image_alt'])){?>
	<div class="item">
	<div class="vedio-desktop">
		<iframe src="https://player.vimeo.com/video/<?php echo trim($banner['image_alt']);?>?autoplay=1&amp;title=0&amp;byline=0" allowfullscreen>
	</iframe>
	
	</div>	
    <div class="vedio-mobile">	
		<iframe src="https://player.vimeo.com/video/<?php echo trim($banner['title2']);?>?autoplay=1&amp;title=0&amp;byline=0" allowfullscreen>
		</iframe>		
	</div>	
    <audio id="player">
	<source src='<?php echo $this->getMediaFolder().'videosound/'.$banner['click_url'] ?>' type='audio/mp3'/>
	</audio>

    <div class="audio-section" id="audio-section">
	<button id="button-on"><img src="<?php echo $this->getMediaFolder(); ?>videosound/s-off.png"></button>
	<button id="button-off"><img src="<?php echo $this->getMediaFolder(); ?>videosound/s-on.png"></button>
	</div>		
	
	    
	</div>
	
	<?php } else {?>
	
	<div class="item"  style="background: url(<?php echo $url_image; ?>)">
                <div class="owl-item-caption">
                 <!--<a href="<?php echo $banner['click_url'] ?>" >  </a>  -->
				 <h1><?php echo $banner['name']; ?></h1>
				
                </div>    
            </div>
	<?php } ?>
            
        
	<?php $i++; ?>            
    <?php endforeach; ?>     
            
        </div>
    </div>
-->

<!--<div class="pt-banner-container">
   <ul class="ptowl"> 
	<?php $i = 1; ?>
    <?php foreach ($banners as $banner): ?>
		
		<?php $url_image = $this->getMediaFolder().$banner['image']; ?>
            <li>
				<?php if($banner['click_url']): ?>
					<a href="<?php echo $banner['click_url'] ?>" class="pt-url">
				<?php endif; ?>
					<img alt="<?php echo $banner['image_alt'] ?>" src="<?php echo $url_image; ?>"/>
				<?php if($banner['click_url']): ?>
					</a>
				<?php endif; ?>
				
				<div id="pt-banner-caption<?php echo $i; ?>" class="pt-caption pt-banner-caption">
					
					<div class="pt-banner-content ptslider-<?php echo $i?>">
						<?php if($banner['name']): ?><h1 class="pt-title1"><?php echo __($banner['name']) ?></h1><?php endif; ?>
						<?php if($banner['title1']): ?><h2 class="pt-title2" ><?php echo __($banner['title1']) ?></h2><?php endif; ?>
						<?php if($banner['description']): ?><div class="pt-banner-des">
							<p><?php echo __($banner['description']) ?></p>
						</div><?php endif; ?>
						<?php if($banner['title2']): ?><h3 class="pt-title3"><?php echo __($banner['title2']) ?></h3><?php endif; ?>
						<?php if($banner['click_url']):?><a href="<?php echo $banner['click_url'] ?>" class="shopnow"><?php echo __('+ shop now')?></a><?php endif;?>
					</div>	
				</div>				
            </li>
		<?php $i++; ?>            
    <?php //endif; ?>            
    <?php endforeach; ?>            
    </ul>
</div>-->
<script type="text/javascript">
	
	require([
	  "jquery",
	  "owlcarousel/minjs"
	 ], function($,owlCarousel){
		$(document).ready(function(){
			$('.front-banner .owl-carousel').owlCarousel({
			loop:true,
			items:1,
			margin:0,
			nav:true,
			dots:false,
			autoplay: false,
			touchDrag: false,
			mouseDrag: false,
			smartSpeed: 900
       
    }) ;
			
		});
	});
</script>
<?php endif; ?>


<style>
footer.page-footer {
    display: none;
}

small.copyright {
    display: none;
}
.breadcrumbs {
    display: none;
}
</style>



<script type="text/javascript">
require([ 'jquery'], function($){

$(document).ready(function(){
/***Desktop Audio button***/
//var button = document.getElementById("audio-section");
var audio = document.getElementById("player");

$('#audio-section').click(function(e){ 
alert('+++');
if(audio.paused){
	alert('+++1');
audio.play();
$('#button-off').hide();
$('#button-on').show();

//button.innerHTML = "<img src=\'/wp-content/uploads/2019/07/s-on.png\' width=\'46px\' height=\'46px\'>"; 
} else {
audio.pause();
alert('+++2');
$('#button-off').show();
$('#button-on').hide();
//button.innerHTML = "<img src=\'/wp-content/uploads/2019/07/s-off.png\' width=\'46px\' height=\'46px\'>";
}
});
});	


	});
</script>






<script type="text/javascript">
    require(['aos'], function (AOS) {
		AOS.init({
                  duration: 1000,
         });	
		
	
	 });
		

</script>	

<style>
.vedio-desktop, .vedio-desktop iframe {
    height: 100vh;
    width: 100vw;
}
div#player {
	width: 100vw;
	height: 100vh !important;
	max-width: 100vw !important;
	min-width: 100vw;
}
.player .vp-video-wrapper .vp-preview { 
	background-size: cover !important;
}

</style>


 <script src="https://player.vimeo.com/api/player.js"></script>
 <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/froogaloop.js"></script>
 
 <section class="video-bg">
        <!-- Video -->
        <iframe src="https://player.vimeo.com/video/347091435?api=1&controls=0&loop=1&background=1&title=0&autoplay=1" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen id="video"></iframe>

        <article>
            <img src="https://new.lv8.com/pub/media/catalog/category/product-slider_1.jpg" alt="" id="fadeImage">
        </article>

        <!-- Sound -->
        <div class="audio">
            <audio id="sound" autoplay>
                <source src="audioloop10.mp3" type="audio/mpeg">
            </audio>
        </div>

        <!-- Audio Button -->
        <div class="audio-button">
            <a href="javascript:void(0)" id="playButton"> 
                <i class="fa fa-play"></i>
            </a>
        </div>

        <!-- Video Button -->
        <div class="video-button">
            <a href="javascript:void(0)" id="playVideo">
                <i class="fa fa-video-camera"></i>
            </a>
            <a href="javascript:void(0)" id="pauseVideo">
                <i class="fa fa-stop"></i>
            </a>
        </div>
  </section>
  
  

<script type="text/javascript">
require([ 'jquery'], function($){

$(document).ready(function(){

var videoButton = document.getElementById("playButton");
var sound = document.getElementById("sound");

videoButton.addEventListener('click', function(){
     if(sound.paused){
        sound.play();
        videoButton.innerHTML='<i class="fa fa-pause"></i>';
     }
     else{
        sound.pause();
        videoButton.innerHTML='<i class="fa fa-play"></i>';
     }
 });

var iframeVideo = document.getElementById('video');
var player = $f(iframeVideo);

$('#playVideo').hide();

$('#pauseVideo').click(function(){
    player.api("pause");
    $('#pauseVideo').hide();
    $('#playVideo').show();
    sound.pause();
    videoButton.innerHTML='<i class="fa fa-play"></i>';
    $('#fadeImage').addClass('fade-image');
});

$('#playVideo').click(function(){
    player.api("play");
    $('#playVideo').hide();
    $('#pauseVideo').show();
    sound.play();
    videoButton.innerHTML='<i class="fa fa-pause"></i>';
    $('#fadeImage').removeClass('fade-image');
});

//Mobile Video
$(window).resize(function(){ 
    if ($(window).width() < 768 || $(window).height() < 480) {
        $(".main iframe").attr("src","https://player.vimeo.com/video/349579635?api=1&controls=0&loop=1&background=1&title=0&autoplay=1");
    }
    else{
        $(".main iframe").attr("src","https://player.vimeo.com/video/347091435?api=1&controls=0&loop=1&background=1&title=0&autoplay=1");
    }
})
});	

});
</script>


<style>
.main {
  position: relative;
  width: 100vw;
  height: 100vh;
}

.main .video-bg {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
  overflow: hidden;
}

.main .video-bg iframe {
  width: 100vw;
  height: 56.25vw;
  min-height: 100vh;
  min-width: 177.77vh;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.main .video-bg article img {
  width: 100%;
  -o-object-fit: cover;
     object-fit: cover;
  height: 100vh;
  z-index: 1;
  position: absolute;
  top: 0;
  left: 0;
  opacity: 0;
  -webkit-transition: 0.8s ease-in-out;
  transition: 0.8s ease-in-out;
}

.main .video-bg .fade-image {
  opacity: 1;
}

.main .video-bg .audio-button {
  position: absolute;
  bottom: 100px;
  left: 100px;
  z-index: 10;
  cursor: pointer;
}

.main .video-bg .audio-button a {
  cursor: pointer;
  font-size: 40px;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
  color: #fff;
}

.main .video-bg .video-button {
  position: absolute;
  bottom: 100px;
  right: 100px;
  z-index: 5;
}

.main .video-bg .video-button a {
  cursor: pointer;
  font-size: 40px;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
  color: #fff;
}

@media screen and (max-width: 767px) {
  .main .video-bg iframe {
    min-width: 100vw;
    min-height: 100vh;
  }
}
  </style>