<div class="cbd-info-title row-full" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
                    <div class="container">
						<div class="information-mobile">
							<span>More Information</span>
						</div>
                        <ul class="info-title-list">
                            <li class="active"><a href="<?php echo $this->getUrl(''); ?>">WHAT IS CBD?</a></li>
                            <li><a href="<?php echo $this->getUrl(''); ?>">HOW OUR CBD <br> PRODUCTS WORK</a></li>
                            <li><a href="<?php echo $this->getUrl(''); ?>">THE VALUE IS IN <br> THE BENEFITS</a></li>
                            <li><a href="<?php echo $this->getUrl(''); ?>">QUALITY <br> MATTERS</a></li>
                            <li><a href="<?php echo $this->getUrl(''); ?>">OUR TOP <br> PRODUCTS</a></li>
                            <li><a href="<?php echo $this->getUrl(''); ?>">RESEARCH</a></li>
                            <li><a href="<?php echo $this->getUrl(''); ?>">FAQS</a></li>
                        </ul>
                    </div>
                </div>