<div class="cbd-info-title row-full">
                    <div class="container">
						<div class="information-mobile">
							<span>More Information</span>
						</div>
                        <ul class="info-title-list">
						
						<?php //echo $_SERVER['REQUEST_URI'] ;?>
 <li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/what-is-cbd')||( $_SERVER['REQUEST_URI']=='/cbdx/what-is-cbd/') )
 {echo 'active';}else{ '';}?>">
 <a href="<?php echo $this->getUrl('cbdx/what-is-cbd'); ?>">WHAT IS CBD?</a>
 </li>
<li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/how-our-cbd-works')||( $_SERVER['REQUEST_URI']=='/cbdx/how-our-cbd-works/') ) {echo 'active';}else{ '';}?>
">
<a href="<?php echo $this->getUrl('cbdx/how-our-cbd-works'); ?>">HOW OUR CBD <br> PRODUCTS WORK</a>
</li>
<li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/the-benefits')||( $_SERVER['REQUEST_URI']=='/cbdx/the-benefits/')) {echo'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cbdx/the-benefits'); ?>">THE VALUE IS IN <br> THE BENEFITS</a>
</li>
<li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/quality-matters')||( $_SERVER['REQUEST_URI']=='/cbdx/quality-matters/') ) {echo 'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cbdx/quality-matters'); ?>">QUALITY <br> MATTERS</a></li>

<li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/top-products')||( $_SERVER['REQUEST_URI']=='/cbdx/top-products/')) {echo 'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cbdx/top-products'); ?>">OUR TOP <br> PRODUCTS</a></li>

<li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/research')||( $_SERVER['REQUEST_URI']=='/cbdx/research/')) {echo 'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cbdx/research'); ?>">RESEARCH</a></li>

<li class="<?php if(( $_SERVER['REQUEST_URI']=='/cbdx/faqs')||( $_SERVER['REQUEST_URI']=='/cbdx/faqs/')) {echo 'active';}else{ '';}?>">
<a href="<?php echo $this->getUrl('cbdx/faqs'); ?>">FAQS</a></li>
                        </ul>
                    </div>
                </div>
				
				
				
				


