<div class="cbd-info-title row-full" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
                    <div class="container">
						<div class="information-mobile">
							<span>More Information</span>
						</div>
                        <ul class="info-title-list">
 <li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/what-is-cbd') 
 {echo 'active';}else{ '';}?>">
 <a href="<?php echo $this->getUrl('cdbx/what-is-cbd'); ?>">WHAT IS CBD?</a>
 </li>
<li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/how-our-cbd-works') {echo 'active';}else{ '';}?>
">
<a href="<?php echo $this->getUrl('cdbx/how-our-cbd-works'); ?>">HOW OUR CBD <br> PRODUCTS WORK</a>
</li>
<li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/the-benefits') {echo'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cdbx/the-benefits'); ?>">THE VALUE IS IN <br> THE BENEFITS</a>
</li>
<li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/quality-matters') {echo 'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cdbx/quality-matters'); ?>">QUALITY <br> MATTERS</a></li>

<li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/top-products') {echo 'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cdbx/top-products'); ?>">OUR TOP <br> PRODUCTS</a></li>

<li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/research') {echo 'active';}else{'';}?>">
<a href="<?php echo $this->getUrl('cdbx/research'); ?>">RESEARCH</a></li>

<li class="<?php if( $_SERVER['REQUEST_URI']=='/cdbx/faqs') {echo 'active';}else{ '';}?>">
<a href="<?php echo $this->getUrl('cdbx/faqs'); ?>">FAQS</a></li>
                        </ul>
                    </div>
                </div>