
<div id="popup-mpdal1" >
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('dosing-chart1')->toHtml(); ?>	
</div>
<div id="popup-mpdal2" >
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('dosing-chart2')->toHtml(); ?>	
</div>
<div id="popup-mpdal3" >
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('dosing-chart3')->toHtml(); ?>	
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal1'));
            $("#dosing-chart1").on('click',function(){
                $("#popup-mpdal1").modal("openModal");
            });

        }
    );
</script>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal2'));
            $("#dosing-chart2").on('click',function(){
                $("#popup-mpdal2").modal("openModal");
            });

        }
    );
</script>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal3'));
            $("#dosing-chart3").on('click',function(){
                $("#popup-mpdal3").modal("openModal");
            });

        }
    );
</script>
	