<?php $vediourl= $this->getNewsvedio();?>
<?php //echo $this->getItem();?>
<?php if(count($vediourl) != '0') { ?>
 <!--<div class="row">-->
 <?php $i= 1; foreach($vediourl as $item_post){?>
 <?php echo $item_post['video_url'];?>
 
 <?php }?>
 
<div class="videoWrapper">
        <iframe allow="encrypted-media" allowfullscreen="" frameborder="0" gesture="media" height="315" src="https://player.vimeo.com/video/<?php echo $item_post['video_url'];?>" width="560">
        </iframe>
	</div>

<?php } else{
	
	echo '<div class="message info empty"><div>Video tutorial not available.</div></div>';
	
}?>


