<?php  $newcategories =$this->getNewpostlist();?>

 <?php foreach($newcategories as $post)
                    $item_post = $post->getData();
				  {?>
<?php  $dataitem  =  $this->getCategriename($item_post['categories'] );
  $categorie_title = $dataitem->getData();
  
  //echo "<pre>";print_r( $categorie_title);
?> 
<div class="col-md-4 col-12">
                           <div class="post-item">
                               <div class="post-image">
                                   <a href="<?php  echo $item_post['id'] ;?>">
                                        <img src="<?php  echo $this->getMediaurl().$item_post['thumbnail'] ;?>" alt="<?php  echo $item_post['post_title']?>" class="img-fluid">         
                                   </a>
                                   
                               </div>
                               <div class="post-info">
                                   <span class="small-title"> <?php echo $categorie_title[0]['categorie_title']; ?></span>
                                   <a href="<?php  echo $this->getUrl('news/index/detail?id='.$item_post['id'].'') ;?>" class="name"><?php echo $item_post['post_title'];?></a>
                               </div>
                           </div>
                       </div>
                       
					   
				  <?php }?>			   
                  					   
                      
                      