<?php  $NewsDetail = $this->getNewsDetail();?>
<?php  $NewsDetail =  $NewsDetail->getData();


//echo $NewsDetail[0]['post_title'].'<br>';
//echo $NewsDetail[0]['thumbnail'].'<br>';
//echo $NewsDetail[0]['url_key'].'<br>';
//echo $NewsDetail[0]['categories'].'<br>';
//echo $NewsDetail[0]['video_url'].'<br>';
//echo $NewsDetail[0]['full_content'];


?>

<div class="news-detail-container">
<div class="news-detail-banner">
		<img src="<?php echo $this->getMediaUrl().$NewsDetail[0]['detailpagebanner'];?>" alt="" class="img-fluid">
</div>
	<div class="news-detail-info">
		<div class="news-detail-title">
			<?php echo $NewsDetail[0]['post_title']; ?>
		</div>
		<?php (!empty($NewsDetail[0]['publish_at'])){?>
		<div class="publish_atdate">
		<?php echo $NewsDetail[0]['publish_at']; ?>
		</div>
		   <?php }?>
    </div>	
		
		
		<div class="news-detail-content">
			<?php echo $NewsDetail[0]['full_content']; ?> 
		</div>
     

	

</div>
