<?php  $newcategories =$this->getNewsAllPost();
$newcategories = $newcategories->getData() ;

//count($newcategories);
//echo "<pre>";print_r( $newcategories);
?>
<?php if(count($newcategories) != '0') { ?>
 <!--<div class="row">-->
 <?php $i= 1; foreach($newcategories as $item_post)
                    //$item_post = $post->getData();
				  //echo"<pre>";print_r($item_post );
				  
				  {?>
				  
                     <div  class="post" id="post_<?php echo $item_post['id']; ?>">
				  <div class="row">
                        <div class="col-lg-6 col-md-6 col-12 left-col">
                            <div class="launches-bx">
                                <h3><?php echo $item_post['post_title']?></h3>
                                <p><?php echo $item_post['short_content']?></p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12 right-col">
                            <div class="launches-vide-col"   onclick="popupFunction(<?php echo $item_post['id']; ?>)"  id="idvedio-<?php echo $item_post['id']; ?>">
                                
								<?php if(!empty($item_post['video_url'])){?>
								<img src="<?php echo $this->getMediaUrl().$item_post['vedioimg']?>" alt="<?php echo $item_post['post_title']?>" class="img-fluid">
                                <?php } else {?>
								<div class="video_url_coming-soon"><span>Coming Soon.</span></div>
								<?php }?>
							</div>
                        </div>
                       
                   
				   
	<!--<div id="header-mpdal<?php echo $item_post['id']; ?>" style="display:none;">
    <div class="videoWrapper">
        <iframe allow="encrypted-media" allowfullscreen="" frameborder="0" gesture="media" height="315" src="https://player.vimeo.com/video/<?php echo $item_post['video_url'];?>" width="560">
        </iframe>
		
		
    </div>
    </div>-->
				   
  <!--<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#header-mpdal<?php echo $item_post['id']; ?>'));
            $("#click-header<?php echo $item_post['id']; ?>").on('click',function(){ 
                $("#header-mpdal<?php echo $item_post['id']; ?>").modal("openModal");
            });

        }
    );
</script>-->
				
                     </div>
				 </div> 
				   
				   
				   
					
				  <?php  $i++; } ?>

                     	
                       
	             
				  
<?php }else {?>

<p> there no Recent News</p>
<?php }?>  




<div id="popup-modal1" style="display:none;">
   <div id="popup-image"></div>

</div>



<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
				removalDelay: 7000 ,
                //title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),        
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
			
            };

            var popup = modal(options, $('#popup-modal1'));
            //function popupFunction(obj){ 
			
			//alert(var obj)
			//$("#popup-modal1").modal("openModal");
            //};

        }
    );
</script>


 <script type="text/javascript">
function popupFunction(obj)
{
jQuery(document).ready(function($){
  //alert(obj);
  var vediourl = $("#idvedio-"+obj).val();
  $("#loderpop").addClass("showpopup");
  //alert(vediourl);
  $.ajax({
        url: "<?php echo $this->getBaseUrl()?>/news/index/Vediotitorial/",
        type: "GET",
        data:  {"id":obj},
        success: function(response){
			//alert(response);
			
		$('#popup-image').html(response);	
		$("#popup-modal1").modal("openModal");
		 $("#loderpop").removeClass("showpopup");
        }
	  });
 
});
}
</script>      

 <script type="text/javascript">
require([ 'jquery'], function($){
$(document).ready(function(){
$('body').on('click','.action-close',function() {
		$('#popup-image').html('');
		//alert('++');
	});
	});
	});
</script>      
	   