<?php  $newcategories =$this->getNewsAllPost();
$newcategories = $newcategories->getData() ;

//count($newcategories);
//echo "<pre>";print_r( $newcategories);
?>
<?php if(count($newcategories) != '0') { ?>
 <!--<div class="row">-->
 <?php $i= 1; foreach($newcategories as $item_post)
                    //$item_post = $post->getData();
				  //echo"<pre>";print_r($item_post );
				  
				  {?>
				  
                        <!--<div class="col-lg-6 col-md-6 col-12 left-col">
                            <div class="launches-bx">
                                <h3><?php echo $item_post['post_title']?></h3>
                                <p><?php echo $item_post['short_content']?></p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12 right-col">
                            <div class="launches-vide-col">
                                <img src="<?php echo $this->getMediaUrl().$item_post['thumbnail']?>" alt="<?php echo $item_post['post_title']?>" class="img-fluid">
                            </div>
                        </div>-->
                       
                   
				   
				  <div  class="post" id="post_<?php echo $item_post['id']; ?>">
				  <div class="row">
                        <div class="col-lg-6 col-md-6 col-12 left-col">
                            <div class="launches-bx">
                                <h3><?php echo $item_post['post_title']?></h3>
                                <p><?php echo $item_post['short_content']?></p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12 right-col">
                            <div class="launches-vide-col"  id="click-header<?php echo $item_post['id']; ?>">
                                <img src="<?php echo $this->getMediaUrl().$item_post['vedioimg']?>" alt="<?php echo $item_post['post_title']?>" class="img-fluid">
                            </div>
                        </div>
                       
                   
				   
	<div id="header-mpdal<?php echo $item_post['id']; ?>" style="display:none;">
    <div class="videoWrapper">
        <iframe allow="encrypted-media" allowfullscreen="" frameborder="0" gesture="media" height="315" src="https://www.youtube.com/embed/<?php echo $item_post['video_url'];?>" width="560">
        </iframe>
    </div>
    </div>
				   
  <script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#header-mpdal<?php echo $item; ?> '));
            $("#click-header<?php echo $item;?>").on('click',function(){ 
                $("#header-mpdal<?php echo $item ;?>").modal("openModal");
            });

        }
    );
</script>
				
                     </div>
				 </div> 
				   
				   
				   
					
				  <?php  $i++; } ?>

                     	
                       
	             
				  
<?php }else {?>

<p> there no Recent News</p>
<?php }?>  




<script>
/*function getLoadmorevideo(page){
	
jQuery(document).ready(function($){
  $("#loderpop").addClass("showpopup");
  	 //var obj = $("#categoriesitem-1").val(); 
	 //var page = $("#categoriesitem-1").val(); 
	 alert(page);
	 //alert(obj)
    $.ajax({
        url: "<?php echo $this->getBaseUrl()?>/news/index/recentvideo/",
        type: "GET",
        data:  {"page":page},
        success: function(response){
		$('#categries-video').html(response);	
		$("#loderpop").removeClass("showpopup");
        }
	  });
 
});
	
}*/
</script>           