<?php  $newcategories =$this->getNewcategories();?>
<?php  $newsFeacture =$this->getNewsFeacture();?>
<?php  $NewsAllPost =$this->getNewsAllPost();?>
<?php  $NewsAllPost1 =$this->getNewsvedio();?>
<?php  $Newsvediocount =$this->getNewsvediocount();?>


<div class="section-notfront">
           
           <!--news-featurd--> 
           <div class="news-featured row-full" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
                <div class="container">
                    <h1>Featured</h1>
                    <div class="owl-carousel owl-theme">
                        
						
						<?php foreach($newsFeacture as $itemFeacture){
							
							$itemsFeacture = $itemFeacture->getData();
							//echo"<pre>";print_r($itemsFeacture );
						?>
                      
                        <div class="item">
                            <div class="craft-higher craft-box-row">
                                <div class="col-md-6 left-col">
                                    <div class="craft-img-col">
                                        <img src="<?php echo $this->getMediaUrl().$itemsFeacture['featuredimg'] ?>" alt="<?php echo $itemsFeacture['post_title'] ?>" class="img-fluid">
                                    </div>
                                </div>
                                <div class="col-md-6 right-col">
                                    <div class="craft-info-col">
                                        <div class="craft-graybx">
                                            <span class="small-title">Featured</span>
                                            <h3><?php echo $itemsFeacture['post_title'] ?></h3>
                                            <p><?php echo $itemsFeacture['short_content'] ?></p>
                                            <a href="<?php echo $this->getUrl('news/index/detail?id='.$itemsFeacture['id'].''); ?>" class="learn-btn read-btn">Read Article</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
						
						<?php }?>

                    </div>
                </div>
           </div> 
           <!--/news-featurd--> 

           <!--latest-posts-->
           <div class="latest-post row-full" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
               <div class="container">
                   <h2>Latest Posts</h2>
                   <div class="filter-category">
                    <span class="fliter-name">Filter by Category</span>
					<ul class="filter-cat-list">
					<?php 
					$i= 1; 
					foreach($newcategories as $categoriesitem){ 
					$item = $categoriesitem->getData();?>
                    <input type="hidden" id="categoriesitem-<?php echo $i?>" value="<?php echo $item['id'];?>">
					<li><a href="javascript:void(0);"   onclick="getCategoryid(<?php echo $item['id'];?>)" ><?php echo $item['categorie_title'];?></a></li>
					<?php $i++;}?>
					</ul>
                   </div>
                  
                       
					  <span id="recent-blog"> </span>
                       
                      
                       

				  
				   
               </div>
           </div>
           <!--/latest-posts-->


           <!--CBDX-launches-->
           <div class="cbdx-launches row-full" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
		   
		   <?php $allcount = count($Newsvediocount);  echo $allcount; ?>
               <div class="container">
			  
                 
			 
					<?php $i= 1; foreach($NewsAllPost1 as $post)
                    $item_post = $post->getData();
				  {?>
				  
				  <div  class="post" id="post_<?php echo $item_post['id']; ?>">
				  <div class="row">
                        <div class="col-lg-6 col-md-6 col-12 left-col">
                            <div class="launches-bx">
                                <h3><?php echo $item_post['post_title']?></h3>
                                <p><?php echo $item_post['short_content']?></p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12 right-col">
                            <div class="launches-vide-col"  id="click-header<?php echo $i;?>">
                                <img src="<?php echo $this->getMediaUrl().$item_post['vedioimg']?>" alt="<?php echo $item_post['post_title']?>" class="img-fluid">
                            </div>
                        </div>
                       
                   
				   
	<div id="header-mpdal<?php echo $i;?>" style="display:none;">
    <div class="videoWrapper">
        <iframe allow="encrypted-media" allowfullscreen="" frameborder="0" gesture="media" height="315" src="https://www.youtube.com/embed/<?php echo $item_post['video_url'];?>" width="560">
        </iframe>
    </div>
    </div>
				   
  <script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#header-mpdal<?php echo $i;?>'));
            $("#click-header<?php echo $i;?>").on('click',function(){ 
                $("#header-mpdal<?php echo $i;?>").modal("openModal");
            });

        }
    );
</script>
				
                     </div>
				 </div> 
				  <?php $i++; } ?>

                       <div class="col-12 read-col">
                            <a href="javascript:void(0);" class="load-more text-link">See More</a>
							<!--<h5 class="load-more">Load More</h5>-->
							<input type="hidden" id="row" value="1">
							<input type="hidden" id="all" value="<?php echo $allcount; ?>">
                       </div>				  
					
               </div>
           </div>
           <!--/CBDX-launches-->
           

           


        </div>
		
		



<script>
function getCategoryid(obj){
	
jQuery(document).ready(function($){
  $("#loderpop").addClass("showpopup");
  var $el = $("categoriesitem"+obj);
  $el.addClass("active").siblings().removeClass('active');
  $.ajax({
        url: "<?php echo $this->getBaseUrl()?>news/index/recent/",
        type: "GET",
        data:  {"id":obj,"page":3},
        success: function(response){
		$('#recent-blog').html(response);	
		$("#loderpop").removeClass("showpopup");
        }
	  });
 
});
	
}

</script>	
<script type="text/javascript">
require([ 'jquery'], function($){
$(document).ready(function(){
	//news page filter category js
    $(".filter-category span.fliter-name").on("click", function(){
        $("ul.filter-cat-list").slideToggle();
    })	
	
	 //var obj = $("categoriesitem-1").val();
	 var obj = $("#categoriesitem-1").val(); 
	 //alert(obj);
	 $.ajax({
        url: "<?php echo $this->getBaseUrl()?>news/index/recent/",
        type: "GET",
        data:  {"id":obj,"page":3},
        success: function(response){
		$('#recent-blog').html(response);	
		//$("#loderpop").removeClass("showpopup");
        }
	  });
	
	
	
	/*$.ajax({
        url: "<?php echo $this->getBaseUrl()?>news/index/recentvideo/",
        type: "GET",
        data:  {"row":1},
        success: function(response){
		$('#categries-video').html(response);	
		//$("#loderpop").removeClass("showpopup");
        }
	  });*/
	
	
	
	
	});
	});
	
	
	
	
</script>	



<script type="text/javascript">
require([ 'jquery'], function($){
	
	$(document).ready(function(){

    // Load more data
    $('.load-more').click(function(){
        var row = Number($('#row').val());
        var allcount = Number($('#all').val());
        row = row + 1;
        
        if(row <= allcount){
            $("#row").val(row);

            $.ajax({
                url: "<?php echo $this->getBaseUrl()?>news/index/recentvideo/",
                type: 'GET',
                data: {row:row},
                beforeSend:function(){
                    $(".load-more").text("Loading...");
                },
                success: function(response){

                    // Setting little delay while displaying new content
                    setTimeout(function() {
                        // appending posts after last post with class="post"
                        $(".post:last").after(response).show().fadeIn("slow");

                        var rowno = row + 1;

                        // checking row value is greater than allcount or not
                        if(rowno > allcount){

                            // Change the text and background
                            $('.load-more').text("Hide");
                            $('.load-more').css("background","darkorchid");
                        }else{
                            $(".load-more").text("Load more");
                        }
                    }, 2000);


                }
            });
        }else{
            $('.load-more').text("Loading...");

            // Setting little delay while removing contents
            setTimeout(function() {

                // When row is greater than allcount then remove all class='post' element after 3 element
                $('.post:nth-child(3)').nextAll('.post').remove().fadeIn("slow");

                // Reset the value of row
                $("#row").val(0);

                // Change the text and background
                $('.load-more').text("Load more");
                $('.load-more').css("background","#15a9ce");

            }, 2000);


        }

    });

});
	
});
</script>		
<script type="text/javascript">
	
	require([
	  "jquery",
	  "owlcarousel/minjs"
	 ], function($,owlCarousel){
		$(document).ready(function(){
			
	$('.news-featured .owl-carousel').owlCarousel({
    loop:true,
    items:1,
    margin:0,
    nav:false,
    dots:true,
    autoplay:false,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    smartSpeed: 500,
   
}) ;

});
	});
</script>




