<?php  $newcategories =$this->getNewpostlist();
$newcategories = $newcategories->getData() ;

count($newcategories);
//echo "<pre>";print_r( $newcategories);
?>
<?php if(count($newcategories) != '0') { ?>
 <div class="row">
                   
 <?php $i=1 ;foreach($newcategories as $item_post)
     //$item_post = $post->getData();
{?>
<?php  $dataitem  =  $this->getCategriename($item_post['categories'] );
  $categorie_title = $dataitem->getData();
  
  //echo "<pre>";print_r( $newcategories->getData() );
?> 
<div class="col-md-4 col-12">
                           <div class="post-item">
                               <div class="post-image">
         <a href="<?php  echo $this->getUrl('news/index/detail/post/'.$item_post['url_key'].'') ;?>">
                                        <img src="<?php  echo $this->getMediaurl().$item_post['thumbnail'] ;?>" alt="<?php  echo $item_post['post_title']?>" class="img-fluid">         
                                   </a>
                                   
                               </div>
                               <div class="post-info">
                                   <span class="small-title"> <?php echo $categorie_title[0]['categorie_title']; ?></span>
         <a href="<?php  echo $this->getUrl('news/index/detail/post/'.$item_post['url_key'].'') ;?>" class="name"><?php echo $item_post['post_title'];?></a>
                               </div>
                           </div>
                       </div>
                       
					   
				  <?php  $x = $i++;  }?>			   
                  					   
    </div>                  
	<div class="col-12 read-col">
	
	 
	 <a href="javascript:void(0);" class="text-link" id="<?php echo ($x +3) ;?>" onclick="getLoadmoreid(<?php echo ($x +3) ;?>)" >Load More</a>
     </div>				  
<?php }else {?>

<p> there no Recent News</p>
<?php }?>  




<script>
function getLoadmoreid(page){
	
jQuery(document).ready(function($){
  $("#loderpop").addClass("showpopup");
  	 var obj = $("#categoriesitem-1").val(); 
	 //var page = $("#categoriesitem-1").val(); 
	 //alert(page);
	 //alert(obj)
     $.ajax({
        url: "<?php echo $this->getBaseUrl()?>/news/index/recent/",
        type: "GET",
        data:  {"id":obj,"page":page},
        success: function(response){
		$('#recent-blog').html(response);	
		$("#loderpop").removeClass("showpopup");
        }
	  });
 
});
	
}
</script>           