<?php
// @codingStandardsIgnoreFile
$enable_module = $block->getConfig('enabled');
if($enable_module!=1) return ;
$title = $block->getConfig('title');
$content = $block->getConfig('content');
$width = $block->getConfig('width'); if(!$width) $width = 500;
$height = $block->getConfig('height'); if(!$height) $height = 400;
$speed = $block->getConfig('speed');
$top = $block->getConfig('margin_top');
$timeout = $block->getConfig('cookie_timeout');
$mediaUrl = $block->getMediaUrl();
$background = $mediaUrl.'logo/'. $block->getConfig('background');
?>
<div id="newsletter_pop_up" class="pt_newsletterpopup"  >

    
    <div class="content newsletter-popup" style ='background-image:url(<?php //echo $background;?>);'>
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-details">
			<div class="descount-model">
				<!--<div class="title"><strong><?php echo $title; ?></strong></div>-->
				<span class="b-close">
					<!--<img src="<?php echo $mediaUrl; ?>themeimage/close-icon.png">-->
					<i class="fa fa-times"></i>
				</span>
				<div class="newspopup-body" style ='background-image:url(<?php echo $background;?>);'>
					<!--<div class="popup-img-field">
						<img src="<?php echo $background;?>">
					</div>-->
					
					<div class="descount-field">
						
						<div id="newsletter-mass"></div>
						
						
						<div class="field newsletter"  id="newsletter-new">
							<label class="label" for="newsletter"><span><?php echo $title; ?> </span></label>
							<h5><?php echo $content; ?></h5>
							<div class="news-control-field">
								<div class="control">
										<input name="email" type="email" id="newsletters"
											placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email') ?>"
											data-validate="{required:true, 'validate-email':true}"/>
								</div>
								 <div class="actions">
									<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Sign up!') ?>" type="submit">
										<span><?php /* @escapeNotVerified */ echo __('Sign up!') ?></span>
									</button>
								</div>
							</div>
						</div>
						
						
						
						<div class="subscribe-bottom">
						    <div class="unsubscribe-massge"><p>Fear not! We don’t spam and you can unsubscribe at any time.</p>
							<p>By submitting this form and clicking logo arrow you accept receiving email updates on LV8 and LV8 brands and agree to the LV8 <a href="<?php echo $this->getUrl('privacy-policy');?>">Privacy Policy</a>.</p>
							</div>
							<div class="custom-control custom-radio">
							<input type="radio" class="custom-control-input" id="newsletter_popup_dont_show_again">
							<label class="custom-control-label" for="newsletter_popup_dont_show_again">By joining, I accept LV8 <a href="<?php echo $this->getUrl('terms-conditions/');?>">Terms & Conditions</a> and agree to receive LV8 marketing emails. You may unsubscribe at anytime.</label>
							</div>
						</div>
					</div>
					
				</div>
			</div>
        </form>
		
    </div>
</div>
<script type ="text/javascript">
require(["jquery"], function($){
		function setCookie(name,value,days)
		{
		  if (days) {
				var date = new Date();
				date.setTime(date.getTime()+(days*24*60*60*1000));
				var expires = "; expires="+date.toGMTString();
			  }
			  else var expires = "";
			  document.cookie = name+"="+value+expires+"; path=/";
		}

		function getCookie(name)
		{
			  var nameEQ = name + "=";
			  var ca = document.cookie.split(';');
			  for(var i=0;i < ca.length;i++) {
				var c = ca[i];
				while (c.charAt(0)==' ') c = c.substring(1,c.length);
				if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
			  }
			  return null;
		}
			
		// setCookie("shownewsletter",'1',1);
		// alert(getCookie("shownewsletter"));

        

		if(getCookie("shownewsletter") != 1){
			$('#newsletter_pop_up').bPopup({
				position: ['auto', <?php if($top != '') echo $top; else echo '120'; ?>],
				speed: <?php if($speed != '') echo $speed; else echo '450' ?>,
				transition: 'slideDown',
				 onOpen: function() {
					 
					 	$('#newsletter_popup_dont_show_again').bind('click', function(){ 
						console.log('click check box');
						console.log(getCookie("shownewsletter"));
						if(getCookie("shownewsletter") != 1){   
							setCookie("shownewsletter",'1',<?php if($timeout!='') echo $timeout;else echo '1' ?>)
						}else{
							setCookie("shownewsletter",'0',<?php if($timeout!='') echo $timeout;else echo '1' ?>)
						}
					}); 
						
				},
           
			
			});
			}
			
			$( "#newsletter_pop_up form" ).submit(function( event ) {
				        //alert('++++');
					setCookie("shownewsletter",'1',<?php if($timeout!='') echo $timeout;else echo '1' ?>);
					setCookie("shownewstext",'1',<?php if($timeout!='') echo $timeout;else echo '1' ?>);
					//alert(getCookie("shownewstext") );
			});
			
		
	$(document).ready(function() {
	 $('#newsletter-validate-details').on('click','.b-close', function(){
			 alert('+++');
			 
	 });	
		
    if(getCookie("shownewstext") == 1){   
	 $("#newsletter-new").addClass('newsletter-hide');
	 $("#newsletter-mass").html('<span>You are in</span>');	
	  $("#newsletter_pop_up").addClass('pop_up_newleet');	
	 //setCookie("shownewsletter",'1',<?php if($timeout!='') echo $timeout;else echo '1' ?>)
	}
     });

 });	 
</script>


<style>
.pop_up_newleet{left: 233px; position: absolute; top: 120px; z-index: 9999; display: block; opacity: 1;}
.newsletter-hide{ display: none;}
</style>