<div class="row">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links')->toHtml(); ?>	
</div>
</footer>		
<!--<script type="text/x-magento-init">
{"*":{"Magento_Customer\/js\/customer-data":{"sectionLoadUrl":"https:\/\/lv8magento.projectdevelopment.co\/customer\/section\/load\/","cookieLifeTime":"3600","updateSessionUrl":"https:\/\/lv8magento.projectdevelopment.co\/customer\/account\/updateSession\/"}}}    
</script>-->







<script>
    require([
        'jquery',
        'froogaloop'
    ], function ($) {
        $(document).ready(function () {
        var videoButton = document.getElementById("playButton");
		var sound = document.getElementById("sound");
          //alert(sound);
		videoButton.addEventListener('click', function(){
			//$('#playButton').addEventListener('click', function(){
			if(sound.paused){
				console.log(sound);
				console.log(sound.paused);
				sound.play();
				videoButton.innerHTML='<img src="https://new.lv8.com/pub/media/images/volume-on.png">';
			}else{
				//alert('+++1');
				console.log(sound+'gihikg');
				//console.log(sound.paused+'gihikg');
				sound.pause();
				videoButton.innerHTML='<img src="https://new.lv8.com/pub/media/images/volume-off.png">';
			}
		 });
 });
    });
</script>		 