<div class="row">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links')->toHtml(); ?>	
</div>
</footer>		
<script type="text/x-magento-init">
{"*":{"Magento_Customer\/js\/customer-data":{"sectionLoadUrl":"https:\/\/new.lv8.com\/customer\/section\/load\/","cookieLifeTime":"3600","updateSessionUrl":"https:\/\/new.lv8.com\/customer\/account\/updateSession\/"}}}    
</script>







		 