<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="footer-container">
    <div class="footer">
        <?= $block->getChildHtml() ?>
        <p class="bugs"><?= /* @escapeNotVerified */ __('Help Us Keep Magento Healthy') ?> - <a
            href="http://www.magentocommerce.com/bug-tracking"
            target="_blank"><strong><?= /* @escapeNotVerified */ __('Report All Bugs') ?></strong></a>
        </p>
        <address><?= /* @escapeNotVerified */ $block->getCopyright() ?></address>
    </div>
</div>
<script type="text/x-magento-init">
{"*":{"Magento_Customer\/js\/customer-data":{"sectionLoadUrl":"https:\/\/new.lv8.com\/customer\/section\/load\/","cookieLifeTime":"3600","updateSessionUrl":"https:\/\/new.lv8.com\/customer\/account\/updateSession\/"}}}    