<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current 
    if(!empty($category)){
    $category_id = $category->getId();
    $parentcategory = $category->getParentCategory()->getId();
	}else{
	 $category_id = '';	
	 $parentcategory ='';
	}
?>  

<div class="nav-sections">
    <div class="nav-sections-items">
             
                <button class="menuBtn bar-button">
                    <span class="menubar menubar1"></span>
                    <span class="menubar menubar2"></span>
                    <span class="menubar menubar3"></span>
                </button>
     
            
            <div class="menu-col-main">
                <ul class="menu-parent">
                    <li class="menu-level menu-home  <?php if(($_SERVER['REQUEST_URI']=='')||($_SERVER['REQUEST_URI']=='/')) {echo "active";}?>">
					<?php //echo $_SERVER['REQUEST_URI'] ; ?>
                        <a href="<?php echo $this->getUrl('')?>" class="">Home</a>
                    </li>
				     
                    <li class="menu-level <?php if(($_SERVER['REQUEST_URI']=='/about/')||($_SERVER['REQUEST_URI']=='/about')) {echo "active";}?>" >
                        <a href="<?php echo $this->getUrl('about')?>" class="">About</a>
                    </li>
					<li class="menu-level <?php if(($_SERVER['REQUEST_URI']=='/cbdx/products/')||($_SERVER['REQUEST_URI']=='/cbdx/products')) {echo "active";}?>" >
                        <a href="<?php echo $this->getUrl('cbdx/products/')?>" class="">Shop</a>
                    </li>
                    <li class="menu-level <?php if(($_SERVER['REQUEST_URI']=='/news/')||($_SERVER['REQUEST_URI']=='/news')) {echo "active";}?>">
                        <a href="<?php echo $this->getUrl('news')?>" class="">News</a>
                    </li>
                    <li class="menu-level <?php if(($_SERVER['REQUEST_URI']=='/careers/')||($_SERVER['REQUEST_URI']=='/careers')) {echo "active";}?>">
                        <a href="<?php echo $this->getUrl('careers')?>" class="">Careers</a>
                    </li>
                    <li class="menu-level <?php if(($_SERVER['REQUEST_URI']=='/contact/')||($_SERVER['REQUEST_URI']=='/contact')) {echo "active";}?>">
                        <a href="<?php echo $this->getUrl('contact')?>" class="">Contact</a>
                    </li>
                    <li class="menu-item labs-menu  <?php if($category_id == '3'){echo 'active';} ?>  <?php if($parentcategory =='3'){echo 'active';}?>">
                        <i class="fa fa-angle-left"></i>
						<?php $catgries = $this->getallcategries(3)?>
						<a href="<?php echo $catgries->getUrl();?>" class="">Labs</a>
                    </li>
                    <li class="menu-item worx-menu <?php if($category_id == '4'){echo 'active';} ?>   <?php if($parentcategory =='4'){echo 'active';}?>">
                        <i class="fa fa-angle-left"></i>
						<?php $catgries = $this->getallcategries(4)?>
                            <a href="<?php echo $catgries->getUrl();?>" class="">Worx</a>
                    </li>
                    <li class="menu-item cbdx-menu <?php if($category_id == '5'){echo 'active';} ?>   <?php if($parentcategory =='5'){echo 'active';}?>">
                        <i class="fa fa-angle-left"></i>
						<?php $catgries = $this->getallcategries(5)?>
                            <a href="<?php echo $catgries->getUrl();?>" class="">CBDX</a>
                    </li>
                    
                </ul>   
            </div>

            <!--menu-items-->
            <div class="menu-items">
             			  <!--menu-front-->
            

			 <div class="navbar-body menu-item-front <?php if(empty($category_id)){echo 'active';}?>">
                    <div class="menu-item-description">
                        <!--<div class="mobile-back-btn">
                            <a href="javascript:void(0);" class=""><i class="fa fa-angle-left"></i></a>
                        </div> -->
                        <div class="menu-inner">
                            <div class="logo-brand">
                                <a href="<?php echo $this->getUrl(''); ?>"><img src="<?php echo $this->getMedia().'theme/lv8-logo2.png'; ?>" alt="lv8" class="img-fluid"></a>
                            </div>
                            <div class="adrs-col">
                                <h4>Miami</h4>
                                <p>LV8 Offices <br>
                                    123 Main Street <br>
                                    Miami, Florida <br>
                                    305.123.4567
                                </p>
                                <p><a class="email-address" href = "mailto: hello@lv8.com">hello@lv8.com</a></p>
								
                            </div>
                            <div class="social-col">
                                <h5>Follow Us</h5>
                                <ul>
                                    <li class="fb"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
                                    <li class="insta"><a href="javascript:void(0);"><i class="fa fa-instagram"></i></a></li>
                                    <li class="twit"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
                                    <li class="linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
                                </ul>
                            </div>    
                        </div>    
                    </div>
                    <div class="menu-image-item">
                        <img src="<?php echo $this->getMedia().'wysiwyg/images/'?>/lv8-menu-img.jpg" alt="" class="img-fluid">
                    </div> 
                </div>
                <!--/menu-front-->

                <!--menu-1-labs-->
 <div class="navbar-body menu-item-labs <?php if($category_id =='3'){echo 'active';}?>  <?php if($parentcategory =='3'){echo 'active';}?>" >

	
	 <div class="menu-item-description">
	 
       <!--<div class="mobile-back-btn">
          <a href="javascript:void(0);" class=""><i class="fa fa-angle-left"></i></a>
        </div> -->
    <div class="menu-inner">
     <div class="logo-brand">
	
	 <?php $catgries = $this->getallcategries(3);?>
      <a href="<?php echo $catgries->getUrl();?>"><img src="<?php echo $this->getMedia().'catalog/category/'.$this->getInnerlogo(3); ?>" alt="" class="img-fluid"></a>
    </div>
    <div class="adrs-col">
	<?php $catgrieslab = $this->getallcategries(3)?>	
	<?php  $subcats = $catgrieslab->getChildrenCategories();?>	
	<ul>
	<?php foreach ($subcats as $subcat) { ?>
	
	<li><a href="<?php echo $subcat->getUrl();?>"><?php echo $subcat->getName()?></a></li>
	<?php }?>
	<li class="scrollMenu-home  <?php if($category_id == $subcat->getId()){echo 'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-our-craft">OUR CRAFT</a></li>
	<li class="scrollMenu-home <?php if($category_id == $subcat->getId()){echo 'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-brands">BRANDS</a></li>
	<li class="scrollMenu <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-our-craft">OUR CRAFT</a></li>
	<li class="scrollMenu <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-brands">BRANDS</a></li>
	</ul>
<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cdbx-brands')->toHtml(); ?>				
<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menu-us-labs')->toHtml(); ?>				
	</div>
     
	 <div class="social-col">
      <h5>Follow Us</h5>
       <ul>
       <li class="fb"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
       <li class="insta"><a href="javascript:void(0);"><i class="fa fa-instagram"></i></a></li>
       <li class="twit"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
       <li class="linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
       </ul>
      </div>    
     </div>    
    </div>
                    
	<div class="menu-image-item">
    <img src="<?php echo $this->getMedia().'catalog/category/'.$this->getNavimage(3); ?>" alt="" class="img-fluid">
    <div class="menu-caption">
	<?php echo $catgrieslab->getDescription();?>
	</div>
	
	</div> 
    </div>
                <!--/menu-1-labs-->

 <!--menu-2-worx-->
 <div class="navbar-body menu-item-worx <?php if($category_id =='4'){echo 'active' ;}?>  <?php if($parentcategory=='4'){echo 'active';}?>">
    <div class="menu-item-description">
     <!--<div class="mobile-back-btn">
     <a href="javascript:void(0);" class=""><i class="fa fa-angle-left"></i></a>
     </div>-->
     <div class="menu-inner">
     <?php $catgrieslab = $this->getallcategries(4)?>   
		<div class="logo-brand">
        <a href="<?php echo $catgrieslab->getUrl();?>"><img src="<?php echo $this->getMedia().'catalog/category/'.$this->getInnerlogo(4); ?>" alt="" class="img-fluid"></a>
        </div>
     <div class="adrs-col">
		
	<?php  $subcats = $catgrieslab->getChildrenCategories();?>	
	<ul>
	<?php foreach ($subcats as $subcat) { ?>
     <li><a href="<?php echo $subcat->getUrl();?>"><?php echo $subcat->getName()?></a></li>
    <?php }?>	
	<li class="scrollMenu-home <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-worx-grid-images">WORK</a></li>
	<li class="scrollMenu-home <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-success-stories">STORIES</a></li>
	<li class="scrollMenu-home <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-the-players">PLAYERS</a></li>
	<li class="scrollMenu-home <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-our-expertise">SKILLS</a></li>
	<!--end-->
	<li class="scrollMenu <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-worx-grid-images">WORK</a></li>
	<li class="scrollMenu <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-success-stories">STORIES</a></li>
	<li class="scrollMenu <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-the-players">PLAYERS</a></li>
	<li class="scrollMenu <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>#scroll-our-expertise">SKILLS</a></li>
	<ul>
<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menu-worx')->toHtml(); ?>				
</div>
    
	<div class="social-col">
      <h5>Follow Us</h5>
       <ul>
        <li class="fb"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
         <li class="insta"><a href="javascript:void(0);"><i class="fa fa-instagram"></i></a></li>
         <li class="twit"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
         <li class="linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
         </ul>
      </div>    
    </div>    
    </div>
    <div class="menu-image-item">
      <img src="<?php echo $this->getMedia().'catalog/category/'.$this->getNavimage(4); ?>" alt="" class="img-fluid">
     <div class="menu-caption">
	<?php echo $catgrieslab->getDescription();?>
	 </div>
	 
	 </div> 
   </div>
  
  <!--/menu-2-worx-->

 <!--menu-3-cbdx-->
  <div class="navbar-body menu-item-cbdx <?php if($category_id =='5'){echo 'active';}?>  <?php if($parentcategory =='5'){echo 'active';}?> <?php if($parentcategory =='9'){echo 'active';}?>">
      <div class="menu-item-description">
       <!--<div class="mobile-back-btn">
         <a href="javascript:void(0);" class=""><i class="fa fa-angle-left"></i></a>
      </div>-->
 <div class="menu-inner">
    <div class="logo-brand">
	<?php $catgrieslab = $this->getallcategries(5)?>
     <a href="<?php echo $catgrieslab->getUrl();?>"><img src="<?php echo $this->getMedia().'catalog/category/'.$this->getInnerlogo(5); ?>" alt="" class="img-fluid"></a>
     </div>
     
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cdbx-brands')->toHtml(); ?>				
     
    <div class="adrs-col">
    <?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menu-cbdx')->toHtml(); ?>				
		
	<?php  $subcats = $catgrieslab->getChildrenCategories();?>	
	<ul>
	<?php foreach ($subcats as $subcat) { ?>
	<?php  
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
      //echo $_category->getData('include_in_menu')    ;    
	if($_category->getData('include_in_menu') == 1){		  
			  ?>
	<?php ///$categ = $subcat->getData();
	//echo"<pre>";print_r($categ);
	?>
     <li class="scrollMenu-home <?php if($category_id== $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>"><?php echo $subcat->getName()?></a></li>
    <?php }}?>	
	
	<?php foreach ($subcats as $subcat) { 
	if($_category->getData('include_in_menu') == 1){
	?>
	<li class="scrollMenu <?php if($category_id == $subcat->getId()){echo'active';} ?>"><a href="<?php echo $subcat->getUrl();?>"><?php echo $subcat->getName()?></a></li>
	<?php }}?>
	</ul>			
	</div>
       
	   <div class="social-col">
         <h5>Follow Us</h5>
           <ul>
            <li class="fb"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
            <li class="insta"><a href="javascript:void(0);"><i class="fa fa-instagram"></i></a></li>
            <li class="twit"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
            <li class="linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
            </ul>
       </div>    
    </div>    
    
	</div>
      <div class="menu-image-item">
        <img src="<?php echo $this->getMedia().'catalog/category/'.$this->getNavimage(5); ?>" alt="" class="img-fluid">
      <div class="menu-caption">
	<?php echo $catgrieslab->getDescription();?>
	  </div>
	  
	  </div> 
   </div>
                <!--/menu-3-cbdx-->


</div>
            <!--/menu-items-->

 </div>
    
</div>

