<?php

$protocol = 'https';
$url = $protocol . "://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];


$parame = $_GET ;


echo count($parame);
if(count($parame)==''0){
?>

<div class="filter-col prize-filter">
                                    <a href="javascript:void(0);" class="filter-link">Sort by Price</a>
                                    <ul class="filter-dropdown">
                                        <li><a href="<?php echo $url; ?>?product_list_order=price">Price: Low to High</a></li>
                                        <li><a href="<?php echo $url; ?>?product_list_order=price&product_list_dir=desc">Price: High to Low</a></li>
                                    </ul>
                                </div>
								
<?php } else {?>
<div class="filter-col prize-filter">
                                    <a href="javascript:void(0);" class="filter-link">Sort by Price</a>
                                    <ul class="filter-dropdown">
                                        <li><a href="<?php echo $url; ?>&product_list_order=price">Price: Low to High</a></li>
                                        <li><a href="<?php echo $url; ?>&product_list_order=price&product_list_dir=desc">Price: High to Low</a></li>
                                    </ul>
                                </div>
<?php } ?>								