<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryId = 9; // YOUR CATEGORY ID
$category = $categoryFactory->create()->load($categoryId);
$childrenCategories = $category->getChildrenCategories();
$protocol = 'https';
$url = $protocol . "://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

$_SERVER['REQUEST_URI'] ;

?>

<div class="product-tab-title" id="pills-tabs">
                    <div class="container">
                        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                            
							<?php if(($_SERVER['REQUEST_URI']=='/cbdx/products/')||($_SERVER['REQUEST_URI']=='/cbdx/products')){?>
							<li class="nav-item">
							<a class="nav-link active" data-toggle="pill" href="<?php echo $this->getUrl('/cbdx/products/');?>" role="tab" aria-controls="pills-home" aria-selected="true"><?php echo 'All Products';?></a>
                            </li>
							<?php } else {?>
							<li class="nav-item">
							<a class="nav-link "  href="<?php echo $this->getUrl('/cbdx/products/');?>" ><?php echo 'All Products';?></a>
                            </li>
							<?php } ?>
							
							<?php foreach($childrenCategories as $child){ ?>
							<?php //echo $child->getUrl() ;?>
							
							
                            <li class="nav-item">
                                <?php if($url == $child->getUrl()){?>
                                <a class="nav-link active" data-toggle="pill" href="<?php echo $child->getUrl();?>" role="tab" aria-controls="pills-home" aria-selected="true"><?php echo $child->getName();?></a>
                                <?php }else{ ?>
                                <a class="nav-link" data-toggle="pill" href="<?php echo $child->getUrl();?>" role="tab" aria-controls="pills-home" aria-selected="false"><?php echo $child->getName();?></a>
                                <?php } ?>
                            </li>
                            <?php } ?>
							
							
							
                        </ul>
                    </div>
</div>
     