<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>



          <div class="craft-graybx">
           <h3>Stay Updated</h3>
          <p>Enter your email to receive special offers and promotions, product tips and news about all our brands</p>
                                
		 <div class="form-group">
         <form class="form subscribe" novalidate action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="post"
         data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">

          <input name="email" class="form-control" type="email" id="newsletter" placeholder="<?= $block->escapeHtml(__('Enter your email')) ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
               
          <button class="action join-btn" title="<?= $block->escapeHtmlAttr(__('Join')) ?>" type="submit">
                <?= $block->escapeHtml(__('Join')) ?>
            </button>
           
        </form>
								
		 </div>
                           
         </div>
         
<div class="newsletter-modal"></div>

<!--<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div> -->


<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        $(function () {
            let subscribeModal = modal({
                type: 'popup',
                title: 'Newsletter Subscription',
                clickableOverlay: true,
                buttons: [{
                    text: 'Dismiss',
                    click: function() {
                        this.closeModal();
                    }
                }]
            }, $('.newsletter-modal'));

            let subscribeForm = $('.form.subscribe');

            $(subscribeForm).on('submit', function(e) {
                e.preventDefault();
                let email = $('#newsletter').val();

                if ($(subscribeForm).valid()) {
                    $.ajax({
                        url: "<?php echo $this->getUrl('newsletter/subscriber/new/');?>",
                        type: 'POST',
                        data: {
                            'email' : email
                        },
                        dataType: 'json',
                        showLoader: true,
                        complete: function(data, status) {
							
                            let response = JSON.parse(data.responseText);
                            //alert(response);
						    $('.newsletter-modal').addClass(response.status);
							$('.newsletter-modal').text(response.message).modal('openModal');
                        }
                    });
                }
            });
        });
    });
</script>