<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= /* @escapeNotVerified */ __('You have no items in your shopping cart.') ?></p>
    <p><?php /* @escapeNotVerified */ echo __('Click <a href="'.$this->getUrl('cbdx/products').'">here</a> to continue shopping.',$block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
	
</div>

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('featured-products-about-us-cbdx')->toHtml(); ?>	
