<?php echo $block->getLayout()->createBlock('Saffron\Bannerslider\Block\Bannerslider')->setTemplate('bannerslider.phtml')->toHtml();?> 


<script>
    require([
        'jquery',
        'froogaloop'
    ], function ($) {
        $(document).ready(function () {
        var videoButton = document.getElementById("playButton");
		var sound = document.getElementById("sound");
          //alert(sound);
		videoButton.addEventListener('click', function(){
			//$('#playButton').addEventListener('click', function(){
			if(sound.paused){
				console.log(sound);
				console.log(sound.paused);
				sound.play();
				videoButton.innerHTML='<img src="<?php echo $this->getMediaurl();?>images/volume-on.png">';
			}else{
				//alert('+++1');
				console.log(sound+'gihikg');
				//console.log(sound.paused+'gihikg');
				sound.pause();
				videoButton.innerHTML='<img src="<?php echo $this->getMediaurl();?>images/volume-off.png">';
			}
		 });
 });
    });
</script>