<?php echo $block->getLayout()->createBlock('Saffron\Bannerslider\Block\Bannerslider')->setTemplate('bannerslider.phtml')->toHtml();?> 

<?php 

   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $medial_url  = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<script>
    require([
        'jquery',
        'froogaloop'
    ], function ($) {
        $(document).ready(function () {
      
          //alert(sound);
        var cli_rl = $('#click_url_u').val();
        //alert(cli_rl);
      if(cli_rl !=""){
		var videoButton = document.getElementById("playButton");
		var sound = document.getElementById("sound");
		videoButton.addEventListener('click', function(){
			//$('#playButton').addEventListener('click', function(){
			if(sound.paused){
				//console.log(sound);
				//console.log(sound.paused);
				sound.play();
				videoButton.innerHTML='<img src="<?php echo $medial_url ;?>images/volume-on.png">';
			}else{
				//alert('+++1');
				//console.log(sound+'gihikg');
				//console.log(sound.paused+'gihikg');
				sound.pause();
				videoButton.innerHTML='<img src="<?php echo $medial_url;?>images/volume-off.png">';
			}
		 });
		 
		 
		 $(".navbar-col .bar-button").on("click", function(){
               //console.log(sound+'gihikg');
			  //console.log(sound.paused+'gihikg');
			   sound.pause();
			   videoButton.innerHTML='<img src="<?php echo $medial_url;?>images/volume-off.png">';
         })
		 
		 
		 
      }
 });
    });
</script>