<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php   $categreisdata = $this->getCategrieslogo();
if(!empty($categreisdata['entity_id'])){ ?>

<?php if($categreisdata['parent_id']=='2'){?>
<?php   $substr1 = $this->getInnerlogo($categreisdata['entity_id']) ; ?>

<a  href="<?php echo $this->getUrl($substr1['url_path']) ; ?>" title="">
<img src="<?php echo $this->getMedia().'catalog/category/'.$categreisdata->getHomelogo(); ?>" title="<?php echo $substr1['name'] ; ?>" alt="<?php echo $substr1['name'] ; ?>" width="275" height="28">
</a>
<?php } else { ?>

<?php  $substr = $this->getInnerlogo($categreisdata['parent_id']) ;

//echo"<pre>";print_r($substr);
?>
<a  href="<?php echo $this->getUrl($substr['url_path']) ;?>" title="">
<img src="<?php echo $this->getMedia().'catalog/category/'.$substr['innerlogo']; ?>" title="<?php echo $substr['name'] ; ?>" alt="<?php echo $substr['name'] ; ?>" width="275" height="28">
</a>
<?php }?>


 
 
<?php } else {?>

<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>


<?php if ($block->isHomePage()):?>

 <a  href="<?= $block->getUrl('') ?>">
 <img src="<?php echo $this->getMedia().'logo/stores/1/lv8-logo.png' ?>"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
		
		
		
<?php else: ?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$checkModule = $request->getModuleName();
if($checkModule == 'cms'){ ?>

<?php  $checkcbdx = (explode("/",$_SERVER['REQUEST_URI'])) ;  ?>
<?php if($checkcbdx[1]=='cbdx' ){ ?>

<a  href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">

  <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
		
<?php }else{?>

<a  href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
  <img src="<?php echo $this->getMedia().'/theme/lv8-logo2.png' ?>"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />

<?php }?>		
		

<?php }else{ ?>
    
<?php echo $_SERVER['REQUEST_URI']; ?>
 <a  href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">

  <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />

	
<?php }
?>


 
		
	
	
		
  
  
  <?php endif ?>
        
<?php if ($block->isHomePage()):?>
    </a>
<?php else:?>
    </a>
<?php endif?>

<?php }?>
 
 

